config/routes.rb
Rails.application.routes.draw do
  get 'yaml_samples/new'
  get 'yaml_samples', to: redirect('/'), status: 302

  resources :yaml_samples

  root 'yaml_samples#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/yaml_sample.rb
class YamlSample
  include ActiveModel::Model
  attr_accessor :text, :file_name

  def initialize(text, file_name = nil)
    @text = text
    @file_name = file_name
  end

  # Validates the syntax of the YAML.
  # Returns a hash containing information about the first error found when
  # parsing the YAML, or nil if no errors are found.
  def errors
    yaml_errors = nil
    begin
      YAML.safe_load(@text, [Symbol])
    rescue Psych::SyntaxError => e
      yaml_errors = {
        line: e.line,
        column: e.column,
        message: e.message
      }
    end
    yaml_errors
  end

  # Determine the locale of the YAML.
  # Based off of rails i18n YAML file structure where the first key
  # is the locale.
  # Returns a symbol of the samples locale, or nil if the yaml is invalid.
  def locale
    return nil if errors

    locale = YAML.safe_load(@text).keys.first
    locale.to_sym
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/yaml_samples_controller.rb
require 'zip'

class YamlSamplesController < ApplicationController
  MAX_FILE_COUNT = 125

  def create
    if yaml_sample_params[:text]
      create_from_text
    elsif yaml_sample_params[:file]
      file_type = yaml_sample_params[:file].content_type
      logger.info file_type
      if file_type == "application/zip"
        create_from_zip_file
      elsif
        create_from_yaml_file
      end
    end
  end

  def create_from_text
    @yaml_sample = YamlSample.new(yaml_sample_params[:text])
    render "yaml_sample"
  end

  def create_from_yaml_file
    yaml_file = yaml_sample_params[:file]
    @yaml_sample = YamlSample.new(yaml_file.read, yaml_file.original_filename)
    render "yaml_sample"
  end

  def create_from_zip_file
    Zip::File.open(yaml_sample_params[:file].open) do |zip_file|
      @yaml_samples = []
      file_count = 0
      zip_file.each do |yaml_file|
        # Don't parse any directories or funky macOS zip things.
        # Only parse YAML files.
        if yaml_file.ftype == :directory ||
           yaml_file.name.match?(/\A(__MACOSX)/) ||
           !yaml_file.name.match?(/(.yml)\z/)
          next
        end
        break if file_count == MAX_FILE_COUNT
        yaml_text = yaml_file.get_input_stream.read
        @yaml_samples << YamlSample.new(yaml_text, yaml_file.name)
        file_count += 1
      end
    end
    render "yaml_samples"
  end

  private

  def yaml_sample_params
    params.require(:yaml_sample).permit(:text, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yaml_samples_helper.rb
module YamlSamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yamlator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/yaml_samples/_yaml_sample.html.erb
<% if @yaml_sample.errors %>
  <% if @yaml_sample.file_name %>
    <h3 style="color:red"><%= @yaml_sample.file_name %></h3>
  <% end %>
  <pre class="prettyprint linenums lang-yaml"><%= @yaml_sample.text %></pre>
  <p>
    <%= t("sample.lint_result.line") + @yaml_sample.errors[:line].to_s %><br>
    <%= t("sample.lint_result.column") + @yaml_sample.errors[:column].to_s %><br>
    <%= t("sample.lint_result.message") + @yaml_sample.errors[:message] %><br>
  </p>
<% else %>
  <% if @yaml_sample.file_name %>
    <h3 style="color:green"><%= @yaml_sample.file_name %></h3>
  <% end %>
  <p><%= t("sample.lint_result.no_error") %></p>
<% end %>

app/views/yaml_samples/new.html.erb
<h1><%= I18n.t('title') %></h1>
<p>
  <%= t("sample.text_entry_header") %>
</p>
<%= form_with scope: :yaml_sample, url: yaml_samples_path, local: true do |form| %>
  <p>
    <%= form.text_area :text, placeholder: t("sample.text_entry_placeholder") %>
  </p>
  <p>
    <%= form.submit t("sample.text_entry_submit") %>
  </p>
<% end %>
<p>
  <%= t("sample.file_upload_header") %>
</p>
<%= form_with scope: :yaml_sample, url: yaml_samples_path, local: true do |form| %>
  <p>
    <%= form.file_field :file %>
  </p>
  <p>
    <%= form.submit t("sample.file_upload_submit") %>
  </p>
<% end %>

app/views/yaml_samples/yaml_sample.html.erb
<%= javascript_include_tag('lang-yaml.js') %>
<%= javascript_include_tag('prettify.js') %>
<%= stylesheet_link_tag('prettify.css') %>

<body onload="PR.prettyPrint()">
<%= render @yaml_sample %>

app/views/yaml_samples/yaml_samples.html.erb
<%= javascript_include_tag('lang-yaml.js') %>
<%= javascript_include_tag('prettify.js') %>
<%= stylesheet_link_tag('prettify.css') %>

<body onload="PR.prettyPrint()">
<% @yaml_samples.each do |sample| %>
  <pre class="prettyprint linenums lang-yaml"><%= sample.text %></pre>
  <p>
    <%= sample.errors %>
  </p>
<% end %>